/mpc_controller:
 ros__parameters:
    radius: 25.0
    cy: 70.0
    traj_length: 50
    timer_period: 0.1
    max_velocity: 10.0
    max_steer_rate: 0.3
    max_delta: 0.3           # 新增参数
    mpc_steps: 4             # 修改为 4 以匹配 MPC 类初始化
    mpc_dt: 0.25
    kcte: 1.1
    kepsi: 2.0
    kev: 0.01
    ksteer_cost: 5.0